# استخدام بيئة Node.js خفيفة
FROM node:18-alpine

# تحديد فولدر الشغل جوه الدوكر
WORKDIR /app

# نسخ ملفات تعريف المكتبات وتثبيتها
COPY package*.json ./
RUN npm install

# نسخ باقي ملفات المشروع
COPY . .

# فتح بورت 3003
EXPOSE 3003

# أمر تشغيل الباك 
CMD ["npm", "start"] 
# (لو الملف الرئيسي عنده اسمه index.js يغير الكلمة دي)
